/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moviereservation;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author umsang-uk
 */
public class DetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailPanel
     */
    public DetailPanel(String detail, String rate) {
        initComponents();
        detailArea.setLineWrap(true);
        if (detail.length() > 200){
            detailArea.setText(detail.substring(0, 200)+"...");
        }else{
            detailArea.setText(detail);
        }
        rateLabel.setText(String.format("%.1f", Float.valueOf(rate)));
    }
    
    public void UpdatePanel(String detail, String rate){
        if (detail.length() > 200){
            detailArea.setText(detail.substring(0, 200)+"...");
        }else{
            detailArea.setText(detail);
        }
        rateLabel.setText(String.format("%.1f", Float.valueOf(rate)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        rateLabel = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,180));

        detailArea.setEditable(false);
        detailArea.setBackground(new Color(0,0,0,0));
        detailArea.setColumns(20);
        detailArea.setForeground(new java.awt.Color(255, 255, 255));
        detailArea.setRows(5);
        detailArea.setWrapStyleWord(true);
        detailArea.setAutoscrolls(false);
        detailArea.setBorder(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("관람평");

        rateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        rateLabel.setForeground(new java.awt.Color(51, 153, 255));
        rateLabel.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detailArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(detailArea, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(rateLabel))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea detailArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rateLabel;
    // End of variables declaration//GEN-END:variables
}
