/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moviereservation;

import java.awt.Color;
import java.awt.Graphics;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author umsang-uk
 */
public class GraphPanel extends javax.swing.JPanel {
    ArrayList<String[]> data;
    
    int h;
    int sum = 0;
	
    
    JLabel[] dateLabel = new JLabel[4];
    JLabel[] valueLabel = new JLabel[4];
    
    Integer[] height = new Integer[4];
    
    int dateX = 35;
    int valueX = 50;

    @Override
    public void paintComponent(Graphics g) {
        dateX = 35;
            super.paintComponent(g);
            g.setColor(Color.BLACK);
            g.drawLine(35, 250, 285, 250);
            g.setColor(new Color(0,204,204));
            if (sum != 0){
                for (int i=0; i<4; i++){
                    h = 250 * height[i] / sum;
                    g.fillRect(dateX, 250-h, 40, h);
                    valueLabel[i] = new JLabel();
                    if(height[i] == 0){
                        valueLabel[i].setBounds(valueX, 230, 20, 20);
                    }else{
                        valueLabel[i].setBounds(valueX, 250-h, 20, 20);
                    }
                    valueLabel[i].setText(Integer.toString(height[i]));
                    add(valueLabel[i]);
                    dateX += 70;
                    valueX += 70;
                }
            }
            /*
             * g.fillRect(30, 100, 25, 10);
             * g.fillRect(86, 76, 25, 40);
             * g.fillRect(146, 86, 25, 20);
             */

            /*
            lblNewLabel_2.setBounds(120, 70-h2, 20, 20);
            lblNewLabel_2.setText(Integer.toString(h2));
            add(lblNewLabel_2);


            lblNewLabel_3.setBounds(190, 70-h3, 20, 20);
            lblNewLabel_3.setText(Integer.toString(h3));
            add(lblNewLabel_3);


            lblNewLabel_4.setBounds(260, 70-h4, 20, 20);
            lblNewLabel_4.setText(Integer.toString(h4));
            add(lblNewLabel_4);
            */
    }


    /**
     * Creates new form GraphPanel
     */
    public void GraphUpdate(ArrayList<String[]> graph) {
        for (int i=0; i<4; i++){
            dateLabel[i] = new JLabel();
            dateLabel[i].setBounds(dateX, 250, 74, 19);
            dateLabel[i].setText(graph.get(i)[0].substring(5));
            height[i] = Integer.valueOf(graph.get(i)[1]);
            //System.out.println(graph.get(i)[0]);
            sum += height[i];
            add(dateLabel[i]);
            dateX += 70;
        }
        /*디버그
        height[1] = 1;
        height[2] = 3;
        sum += height[1];
        sum += height[2];
        */
        repaint();
    }
    
    public GraphPanel() {
        initComponents();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
