package moviereservation;


import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author umsang-uk
 */
public class LoginDlg extends javax.swing.JDialog {
    
    public boolean isLoginSuccess = false;
    public String id, name;
    DBManager dbManager;

    /**
     * Creates new form loginDlg
     * @param parent
     * @param modal
     */
    public LoginDlg(java.awt.Frame parent, boolean modal, DBManager dbManager) {
        super(parent, modal);
        initComponents();
        this.jIDText.setText("아이디");
        this.jPasswordText.setText("****");
        // MainFrame에서 불러온 DB연결값 불러오기
        this.dbManager = dbManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jIDText = new moviereservation.IdText();
        jPasswordText = new moviereservation.PasswordText();
        jPanel3 = new javax.swing.JPanel();
        jLoginBtn = new javax.swing.JButton();

        jButton1.setText("회원가입");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jIDText.setText("아이디");
        jIDText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jIDTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jIDTextFocusLost(evt);
            }
        });
        jIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIDTextActionPerformed(evt);
            }
        });
        jPanel2.add(jIDText);

        jPasswordText.setText("****");
        jPasswordText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordTextFocusLost(evt);
            }
        });
        jPanel2.add(jPasswordText);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 50));

        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 7));

        jLoginBtn.setText("로그인");
        jLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginBtnActionPerformed(evt);
            }
        });
        jPanel3.add(jLoginBtn);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("로그인 시도");
        id = this.jIDText.getText();
        String pw = new String(this.jPasswordText.getPassword());
        String sql = "select * from user where user_id='"+id+"' and password='"+pw +"'";
        ArrayList<String[]> list = dbManager.executeQuery(sql);
        
        if (!list.isEmpty()){
            isLoginSuccess = true;
            this.dispose();
        } else {
            isLoginSuccess = false;
            JOptionPane.showMessageDialog(null, "아이디 또는 비밀번호가 일치하지 않습니다.", "로그인 실패", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jLoginBtnActionPerformed

    private void jIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIDTextActionPerformed

    private void jIDTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jIDTextFocusGained
        // TODO add your handling code here:
        if(this.jIDText.getText().equals("아이디")){
            this.jIDText.setDefaultText("");
        }
    }//GEN-LAST:event_jIDTextFocusGained

    private void jIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jIDTextFocusLost
        // TODO add your handling code here:
        if(this.jIDText.getText().trim().length() == 0){
            this.jIDText.setText("아이디");
        }
    }//GEN-LAST:event_jIDTextFocusLost

    private void jPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordTextActionPerformed

    private void jPasswordTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordTextFocusGained
        // TODO add your handling code here:
        if ((new String(this.jPasswordText.getPassword())).equals("****")) {
                this.jPasswordText.setText("");
        }
    }//GEN-LAST:event_jPasswordTextFocusGained

    private void jPasswordTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordTextFocusLost
        // TODO add your handling code here:
        if ((new String(this.jPasswordText.getPassword())).length() == 0) {
            this.jPasswordText.setDefaultText("****");
        }
    }//GEN-LAST:event_jPasswordTextFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JoinDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JoinDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JoinDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JoinDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JoinDlg dialog = new JoinDlg(true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private moviereservation.IdText jIDText;
    private javax.swing.JButton jLoginBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private moviereservation.PasswordText jPasswordText;
    // End of variables declaration//GEN-END:variables
}
