/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviereservation;

import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;

/**
 *
 * @author umsang-uk
 */
public class MovieDetailFrame extends javax.swing.JFrame {
    DBManager dbManager;

    String sql_rate = 
        "SELECT *\n" +
        "FROM (SELECT md.Movie_ID, md.Movie_Name, md.Movie_Director, md.Movie_Actor, md.Movie_Genre, md.Movie_Describe, md.Movie_Opening, md.Movie_RunningTime, md.Movie_Poster, r.rate, (@rank := @rank+1) AS ranking\n" +
        "FROM (SELECT @rank := 0) AS b, reviewview r , Movie_Detail AS md LEFT OUTER JOIN (\n" +
        "SELECT w.Movie_ID, sum(w.Reserved) AS total\n" +
        "FROM watchedview w\n" +
        "GROUP BY w.Movie_ID\n" +
        ") AS c\n" +
        "ON md.Movie_ID = c.Movie_ID\n" +
        "where md.Movie_ID = r.Movie_ID\n" +
        "ORDER BY total DESC\n" +
        ") AS a\n" +
        "WHERE a.Movie_ID = %s;";
    
    String sql_watched =
        "SELECT sum(Reserved) \n" +
        "FROM watchedview w \n" +
        "WHERE w.Movie_ID = %s\n" +
        "GROUP BY w.Movie_ID;";
    
    String sql_recent_watch = 
        "SELECT w.Movie_Date, w.Reserved \n" +
        "FROM watchedview w\n" +
        "WHERE w.Movie_ID = %s\n" +
        "AND w.Movie_Date = '%s';";
    
    LocalDate nowDate = LocalDate.now();
    LocalDate prevDate = LocalDate.of(nowDate.getYear(), nowDate.getMonthValue(), nowDate.getDayOfMonth()-3);

    ArrayList<String[]> detail;
    ArrayList<String[]> graph = new ArrayList<>(4);
    
    Boolean isLogin = false;
    /**
     * Creates new form MovieDetailFrame
     */
    public MovieDetailFrame(DBManager dbManager, String movie_id, Boolean isLogin, String user_id) {
        this.dbManager = dbManager;
        this.isLogin = isLogin;
        String watched;
        detail = dbManager.executeQuery(String.format(sql_watched, movie_id));
        if (detail.isEmpty()){
            watched = "0";
        }else{
            watched = detail.get(0)[0];
        }
        for (int i=0; i<4; i++){
            detail = dbManager.executeQuery(String.format(sql_recent_watch, movie_id, prevDate));
            if (detail.isEmpty()){
                graph.add(new String[] {prevDate.toString(), "0"});
            }else{
                graph.add(detail.get(0));
            }
            prevDate = prevDate.plusDays(1);
            System.out.println(graph.get(i)[0] + " " + graph.get(i)[1]);
        }
        detail = dbManager.executeQuery(String.format(sql_rate, movie_id));
        initComponents();
        movieDetailPanel.DetailUpdate(detail.get(0), watched, graph, dbManager, user_id);
    }

    MovieDetailFrame() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        movieDetailPanel = new moviereservation.MovieDetailPanel1(isLogin);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jScrollPane1.setViewportView(movieDetailPanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jScrollPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieDetailFrame(DBManagerMySql.getinstance(), "1", false, "test").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private moviereservation.MovieDetailPanel1 movieDetailPanel;
    // End of variables declaration//GEN-END:variables
}
