/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviereservation;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author umsang-uk
 */
public class MovieListFrame extends javax.swing.JFrame {
    ArrayList<String[]> data;
    MovieListPanel[] moviePanel;
    DBManager dbManager;
    Boolean isLogin;
    String user_id;

    /**
     * Creates new form MovieListFrame
     */
    public MovieListFrame(ArrayList<String[]> movieDatas, DBManager dbManager, Boolean isLogin, String user_id){
        this.data = movieDatas;
        this.dbManager = dbManager;
        this.isLogin = isLogin;
        this.user_id = user_id;
        initComponents();
        myPageBtn.setVisible(false);
        
        if (user_id != null){
            isLogin = true;
            logBtn.setText("로그아웃");
            myPageBtn.setVisible(true);
            joinBtn.setVisible(false);
        }
        
        posterPanel1.d = new Dimension(223, 53);
        try {
            posterPanel1.DrawImg(ImageIO.read(HomeFrame.class.getResource("logo.png")));
        } catch (IOException ex) {
            Logger.getLogger(MovieListFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) { 
                    new HomeFrame(dbManager, user_id).setVisible(true);
                    dispose();
            }
        });
        moviePanel = new MovieListPanel[movieDatas.size()];
        for (int i=0; i < movieDatas.size(); i++){
            moviePanel[i] = new MovieListPanel();
            moviePanel[i].updatePanel(movieDatas.get(i));
            //moviePanel[i].addMouseListener(new PosterEnter());
            moviePanel[i].addMouseListener(new PosterEnter());
            listPanel.add(moviePanel[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logBtn = new javax.swing.JButton();
        joinBtn = new javax.swing.JButton();
        posterPanel1 = new moviereservation.PosterPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPanel = new javax.swing.JPanel();
        myPageBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logBtn.setText("로그인");
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });

        joinBtn.setText("회원가입");
        joinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout posterPanel1Layout = new javax.swing.GroupLayout(posterPanel1);
        posterPanel1.setLayout(posterPanel1Layout);
        posterPanel1Layout.setHorizontalGroup(
            posterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );
        posterPanel1Layout.setVerticalGroup(
            posterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        listPanel.setBackground(new java.awt.Color(255, 255, 255));
        listPanel.setMaximumSize(new java.awt.Dimension(811, 32767));
        listPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 5));
        jScrollPane1.setViewportView(listPanel);

        myPageBtn.setText("마이페이지");
        myPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myPageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(posterPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(myPageBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinBtn)
                .addGap(8, 8, 8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(posterPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logBtn)
                        .addComponent(joinBtn)
                        .addComponent(myPageBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        if (evt.getActionCommand().equals("로그인")){
            LoginDlg loginDlg = new LoginDlg(this, true, dbManager);
            loginDlg.setVisible(true);
            if (loginDlg.isLoginSuccess == true) {
                logBtn.setText("로그아웃");
                joinBtn.setVisible(false);
                myPageBtn.setVisible(true);
                isLogin = true;
                user_id = loginDlg.id;
                System.out.println(user_id);
            }
        }else if (evt.getActionCommand().equals("로그아웃")){
            logBtn.setText("로그인");
            joinBtn.setVisible(true);
            myPageBtn.setVisible(false);
            user_id = null;
            isLogin = false;
        }
    }//GEN-LAST:event_logBtnActionPerformed

    private void myPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myPageBtnActionPerformed
        // TODO add your handling code here:
        new MyPageFrame(dbManager, user_id).setVisible(true);
        dispose();
    }//GEN-LAST:event_myPageBtnActionPerformed

    private void joinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinBtnActionPerformed
        // TODO add your handling code here:
        JoinDlg joinDlg = new JoinDlg(true, dbManager);
        joinDlg.setVisible(true);
    }//GEN-LAST:event_joinBtnActionPerformed
                                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieListFrame().setVisible(true);
            }
        });
        */
    }   
    
    class PosterEnter implements MouseListener{
    JPanel panel;

    @Override
    public void mouseClicked(MouseEvent e) {
        panel = (JPanel)e.getSource();
        int idx = Arrays.asList(moviePanel).indexOf(panel);
        new MovieDetailFrame(dbManager, data.get(idx)[0], isLogin, "test").setVisible(true);
        dispose();
    }

    @Override
    public void mousePressed(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton joinBtn;
    private javax.swing.JPanel listPanel;
    private javax.swing.JButton logBtn;
    private javax.swing.JToggleButton myPageBtn;
    private moviereservation.PosterPanel posterPanel1;
    // End of variables declaration//GEN-END:variables
}
