/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviereservation;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author umsang-uk
 */
public class SeatFrame extends javax.swing.JFrame {
    private static DBManager dbManager = DBManagerMySql.getinstance();
    
    String sql_countSeat = 
        "SELECT COUNT(s.Seat_ID)\n" +
        "FROM Reservation r, Seat s\n" +
        "WHERE r.Time_ID = %s\n" +
        "AND r.Reservation_ID = s.Reservation_ID\n" +
        "GROUP BY r.Time_ID;";
    
    String sql_reservedSeat = 
        "SELECT s.Seat_X, s.Seat_Y\n" + 
        "FROM Reservation r, Seat s\n" +
        "WHERE r.Time_ID = %s\n" +
        "AND r.Reservation_ID = s.Reservation_ID;";
    
    
    JButton[][] seatBtn;
    JLabel[] rowLabel;
    // 디버그
    //0 : r.StartTime, 1 : r.EndTime, 2 : r.Movie_Name, 3 : r.Movie_Count, 4 : r.Room_No, 5 : r.Total_Seat, 6 : r.Time_ID, 7:r.Theart_Name, 8:r.Seat_Row
    static String[] Debugdata = {"09:00:00", "11:41:00", "블랙 팬서: 와칸다 포에버", "3", "3", "25", "3", "영진 시네마", "5", "5", "2022-11-19"};
    /**
     * Creates new form testFrame
     */
    public SeatFrame(String[] data) {
        initComponents();
        Screen.setOpaque(true);
        Screen.setBackground(new Color(0,51,102));
        this.setSize(1200, 800);
        this.setVisible(true);
        
        // 예매 정보
        MovieNameLabel.setText(data[2]);
        TheaterLocationLabel.setText(data[7]);
        RoomLabel.setText(data[4]+"관");
        DateLabel.setText(data[10]);
        int x = Integer.parseInt(data[8]);
        int y = Integer.parseInt(data[9]);
        
        // 좌석
        seatBtn = new JButton[x][y+1];
        rowLabel = new JLabel[x];
        for (int i=0; i < x; i++){
            rowLabel[i] = new JLabel(Character.toString((char)(i+65)));
            rowLabel[i].setHorizontalAlignment(JLabel.CENTER);
            SeatPanel.add(rowLabel[i]);
            for (int j=0; j < y; j++){
                seatBtn[i][j] = new JButton(i + ", " + j);
                SeatPanel.add(seatBtn[i][j]);
            }
        }
        
        ArrayList<String[]> reservedSeat = dbManager.executeQuery(String.format(sql_reservedSeat, data[6]));
        int rX, rY;
        for (int i=0; i < reservedSeat.size(); i++){
            rX = Integer.parseInt(reservedSeat.get(i)[0]);
            rY = Integer.parseInt(reservedSeat.get(i)[0]);
            seatBtn[rX][rY].setEnabled(false);
        }
        
        ArrayList<String[]> totalSeat = dbManager.executeQuery(String.format(sql_countSeat, data[6]));
        //System.out.println(totalSeat.get(0)[0]);
        if (totalSeat.isEmpty()){
            SeatInfoLabel.setText("0/" + data[5]);
        }else{
            SeatInfoLabel.setText(totalSeat.get(0)[0] + "/" + data[5]);
        }
                
        
        this.SeatPanel.setLayout(new GridLayout(x, y));
        this.SeatPanel.setPreferredSize(new Dimension(700, 400));
        //SeatPanel.setSize(1000, 1000);
        
        // 이벤트
        TeenM.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                AdultCnt.setText("");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        MovieNameLabel = new javax.swing.JLabel();
        TheaterLocationLabel = new javax.swing.JLabel();
        RoomLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        Poster = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SeatPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        SeatInfoLabel = new javax.swing.JLabel();
        Screen = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdultCnt = new javax.swing.JLabel();
        AdultM = new javax.swing.JButton();
        AdultP = new javax.swing.JButton();
        TeenM = new javax.swing.JButton();
        TeenCnt = new javax.swing.JLabel();
        TeenP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        OtherM = new javax.swing.JButton();
        OtherCnt = new javax.swing.JLabel();
        OtherP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 1200, 800));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1200, 800));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(455, 800));
        jPanel1.setSize(new java.awt.Dimension(455, 800));

        MovieNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        MovieNameLabel.setText("jLabel7");

        TheaterLocationLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        TheaterLocationLabel.setText("jLabel8");

        RoomLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        RoomLabel.setText("jLabel9");

        DateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        DateLabel.setText("jLabel10");

        Poster.setText("jLabel11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(MovieNameLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoomLabel)
                            .addComponent(TheaterLocationLabel)
                            .addComponent(DateLabel))))
                .addContainerGap(340, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Poster)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(MovieNameLabel)
                .addGap(25, 25, 25)
                .addComponent(TheaterLocationLabel)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Poster)
                    .addComponent(RoomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        SeatPanel.setBackground(new java.awt.Color(255, 255, 255));
        SeatPanel.setPreferredSize(new java.awt.Dimension(700, 400));
        SeatPanel.setSize(new java.awt.Dimension(703, 543));

        javax.swing.GroupLayout SeatPanelLayout = new javax.swing.GroupLayout(SeatPanel);
        SeatPanel.setLayout(SeatPanelLayout);
        SeatPanelLayout.setHorizontalGroup(
            SeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        SeatPanelLayout.setVerticalGroup(
            SeatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jLabel7.setText("좌석현황");

        SeatInfoLabel.setText("jLabel8");

        Screen.setBackground(new java.awt.Color(0, 51, 102));
        Screen.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Screen.setForeground(new java.awt.Color(255, 255, 255));
        Screen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Screen.setText("SCREEN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel7)
                        .addGap(120, 120, 120)
                        .addComponent(SeatInfoLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Screen, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Screen)
                .addGap(48, 48, 48)
                .addComponent(SeatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SeatInfoLabel))
                .addGap(51, 51, 51))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel1.setText("성인");

        AdultCnt.setFont(new java.awt.Font("Helvetica Neue", 0, 28)); // NOI18N
        AdultCnt.setText("0");

        AdultM.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        AdultM.setText("<");
        AdultM.setBounds(new java.awt.Rectangle(0, 0, 30, 30));
        AdultM.setSize(new java.awt.Dimension(30, 30));

        AdultP.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        AdultP.setText(">");

        TeenM.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        TeenM.setText("<");

        TeenCnt.setFont(new java.awt.Font("Helvetica Neue", 0, 28)); // NOI18N
        TeenCnt.setText("0");

        TeenP.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        TeenP.setText(">");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel2.setText("청소년");

        OtherM.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        OtherM.setText("<");

        OtherCnt.setFont(new java.awt.Font("Helvetica Neue", 0, 28)); // NOI18N
        OtherCnt.setText("0");

        OtherP.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        OtherP.setText(">");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel3.setText("우대");

        jButton1.setText("초기화");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdultM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdultCnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdultP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TeenM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TeenCnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TeenP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OtherM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OtherCnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OtherP)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AdultM)
                    .addComponent(jLabel1)
                    .addComponent(AdultCnt)
                    .addComponent(AdultP)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(TeenM)
                        .addComponent(jLabel2)
                        .addComponent(TeenCnt)
                        .addComponent(TeenP)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(OtherM)
                            .addComponent(jLabel3)
                            .addComponent(OtherCnt)
                            .addComponent(OtherP)
                            .addComponent(jButton1))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
 
    
    // 디버그
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatFrame(Debugdata).setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdultCnt;
    private javax.swing.JButton AdultM;
    private javax.swing.JButton AdultP;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel MovieNameLabel;
    private javax.swing.JLabel OtherCnt;
    private javax.swing.JButton OtherM;
    private javax.swing.JButton OtherP;
    private javax.swing.JLabel Poster;
    private javax.swing.JLabel RoomLabel;
    private javax.swing.JLabel Screen;
    private javax.swing.JLabel SeatInfoLabel;
    private javax.swing.JPanel SeatPanel;
    private javax.swing.JLabel TeenCnt;
    private javax.swing.JButton TeenM;
    private javax.swing.JButton TeenP;
    private javax.swing.JLabel TheaterLocationLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
